name: Deploy sonIQue to AWS
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          CI: false
          VITE_AWS_REGION: ${{ secrets.VITE_AWS_REGION }}
          VITE_AWS_ACCESS_KEY_ID: ${{ secrets.VITE_AWS_ACCESS_KEY_ID }}
          VITE_AWS_SECRET_ACCESS_KEY: ${{ secrets.VITE_AWS_SECRET_ACCESS_KEY }}
          VITE_COGNITO_USER_POOL_ID: ${{ secrets.VITE_COGNITO_USER_POOL_ID }}
          VITE_COGNITO_CLIENT_ID: ${{ secrets.VITE_COGNITO_CLIENT_ID }}
          VITE_DYNAMODB_TABLE_PREFIX: ${{ secrets.VITE_DYNAMODB_TABLE_PREFIX }}
          VITE_BEDROCK_MODEL_ID: ${{ secrets.VITE_BEDROCK_MODEL_ID }}
          VITE_S3_BUCKET: ${{ secrets.VITE_S3_BUCKET }}
          VITE_QUIZ_API_KEY: ${{ secrets.VITE_QUIZ_API_KEY }}
          REACT_APP_API_ENDPOINT: ${{ secrets.REACT_APP_API_ENDPOINT }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to S3
        run: |
          echo "Deploying to S3..."
          aws s3 sync dist/ s3://sonique --delete
          echo "S3 deployment complete"

      - name: Invalidate CloudFront Cache
        run: |
          echo "Invalidating CloudFront cache..."
          aws cloudfront create-invalidation \
            --distribution-id E2HE4B6TLUWYNY \
            --paths "/*"
          echo "Cache invalidation initiated"

      - name: Wait for Invalidation
        run: |
          echo "Waiting for CloudFront invalidation to complete..."
          sleep 30
